version: "3.9"

services:
  db-ia-boilerplate:
    image: postgres:17.4
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-network

  ia-boilerplate:
    build:
      context: .
    image: ia-boilerplate
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db-ia-boilerplate:
        condition: service_healthy
    networks:
      - go-network
volumes:
  pgdata:

networks:
  go-network:
    driver: bridge
